services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_vagas
    ports:
      - 5432:5432